[package]
name = "bxt-rs"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitflags = "1.2.1"
libc = "0.2.70"
log = "0.4.8"
pretty_env_logger = "0.4.0"
