[package]
name = "bxt-rs"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitflags = "1.2.1"
libc = "0.2.70"
libloading = "0.6.7"
log = "0.4.8"
serde_json = "1.0.53"
serde = "1.0.110"
env_logger = { version = "0.7.1", default-features = false, features = ["termcolor", "atty"] }
bxt-macros = { path = "bxt-macros" }
bxt-patterns = { path = "bxt-patterns" }

[target."cfg(windows)".dependencies]
minhook-sys = { git = "https://github.com/YaLTeR/minhook-sys.git" }
once_cell = "1.4.0"

[target."cfg(windows)".dependencies.winapi]
version = "0.3.8"
features = ["libloaderapi", "psapi", "winuser", "synchapi", "handleapi", "processthreadsapi"]

[profile.dev.package.bxt-patterns]
opt-level = 3

[workspace]
members = [".", "bxt-macros", "bxt-patterns"]
