[package]
name = "bxt-rs"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitflags = "1.2.1"
libc = "0.2.70"
libloading = "0.6.7"
log = "0.4.8"
serde_json = "1.0.53"
serde = "1.0.110"
bxt-macros = { path = "bxt-macros" }
bxt-patterns = { path = "bxt-patterns" }
simplelog = "0.9.0"
color-eyre = { version = "0.5.0", default-features = false }
once_cell = "1.4.0"
ash = "0.31.0"
rust_hawktracer = "0.7.0"
thiserror = "1.0.23"
byte-slice-cast = "1.0.0"
crossbeam-channel = "0.5.0"
git-version = "0.3.4"

[target."cfg(windows)".dependencies.simplelog]
version = "0.9.0"
default-features = false

[target."cfg(windows)".dependencies]
minhook-sys = "0.1.0"

[target."cfg(windows)".dependencies.winapi]
version = "0.3.8"
features = ["libloaderapi", "psapi", "winuser", "synchapi", "handleapi", "processthreadsapi"]

[profile.dev.package.bxt-patterns]
opt-level = 3

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
debug = 1 # For lines in backtraces.

[workspace]
members = [".", "bxt-macros", "bxt-patterns"]

[build-dependencies]
gl_generator = "0.14.0"

[features]
vulkan-debug = []
profiling = ["rust_hawktracer/profiling_enabled"]

# Builds bxt-rs that can be injected alongside the original BXT
# for capturing TASes.
bxt-compatibility = []
