[package]
name = "bxt-strafe"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.2"
glam = "0.20.2"
hltas = "0.5.0"
ordered-float = "2.10.0"
tap = "1.0.1"

[dev-dependencies]
ncollide3d = "0.32.0"
proptest = "1.0.0"
proptest-derive = "0.3.0"
