name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *' # Monthly

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [stable, beta]
        features: ['', vulkan-debug, profiling, 'vulkan-debug,profiling']

        include:
          - os: ubuntu-latest
            label: Ubuntu
            target: i686-unknown-linux-gnu
            filename: libbxt_rs.so

          - os: windows-latest
            label: Windows
            target: i686-pc-windows-msvc
            filename: bxt_rs.dll

    name: ${{ matrix.rust }} - ${{ matrix.label }} - ${{ matrix.features }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libc6-dev-i386 lib32stdc++-7-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --features=${{ matrix.features }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.target }} --features=${{ matrix.features }}

      - uses: actions/upload-artifact@v2
        if: matrix.rust == 'stable'
        with:
          name: bxt-rs-${{ runner.os }}-${{ matrix.configuration }}-${{ matrix.features }}
          path: target/${{ matrix.target }}/debug/${{ matrix.filename }}

  clippy:
    strategy:
      fail-fast: false

      matrix:
        include:
          - os: ubuntu-latest
            label: Ubuntu
            target: i686-unknown-linux-gnu

          - os: windows-latest
            label: Windows
            target: i686-pc-windows-msvc

    name: clippy - ${{ matrix.label }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: ${{ matrix.target }}
          components: clippy

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --target ${{ matrix.target }}

  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: nightly
          components: rustfmt

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
